name: Run SEO Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 0' # 毎週月曜日 0:00 (JST) [＝日曜 15:00 (UTC)] に自動実行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v5

      - name: Pythonセットアップ
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: 依存ライブラリ導入とPython自動投稿の実行
        env:
          LIVEDOOR_ID: ${{ secrets.LIVEDOOR_ID }}
          ATOMPUB_PASSWORD: ${{ secrets.ATOMPUB_PASSWORD }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python auto_post.py
